=== ana2782617/UBB/Web/lab_4/collection.dtd
<!ELEMENT collection (album+)>
<!ELEMENT album (title,artist+,year)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT artist (#PCDATA)>
<!ELEMENT year (#PCDATA)>

<!ATTLIST album type CDATA #REQUIRED>

=== ana2782617/UBB/Web/lab_4/music.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE collection SYSTEM "collection.dtd"> -->
<!--<?xml-stylesheet type="text/css" href="book.css"?>-->
<!-- <?xml-stylesheet type="text/xsl" href="music.xsl"?> -->

<collection>
    <album type="CD">
        <title>Ana</title>
        <artist>Maria</artist>
        <year>1997</year>
    </album>
    <album type="CD">
        <title>Ana2</title>
        <artist>Maria</artist>
        <year>2000</year>
    </album>
    <album type="Tape">
        <title>Ana</title>
        <artist>Maria</artist>
        <year>1997</year>
    </album>
    <album type="Vinyl">
        <title>Ana</title>
        <artist>Maria</artist>
        <year>1997</year>
    </album>

</collection>
